application: wallpile
version: 1
runtime: python
api_version: 1

handlers:

- url: /(favicon\.ico|robots\.txt)
  static_files: static/$1
  upload: static/$1

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static
  secure: optional

- url: .*
  script: main.py
